baseURL = 'https://james-s-w-clark.github.io/l2-lyrics/'
languageCode = 'en-us'
title = 'L2 Lyrics'
theme = 'l2-lyrics'

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser]
attribute = true
autoHeadingID = true
